### ISSUE TITLE
No routes matches [GET] "/rack_session/edit"

### ISSUE THREAD

**Issue by C404** [railsware/rack_session_access#17]
Hi,

I just installed your gem with capybara and required "rack_session_access/capybara" in my spec_helper.rb

Yet when i run the test with the following code : 
```
  context "when visitor tracked repositories" do
    it "should see tracked repository list" do
      page.set_rack_session(user_id: 33)
      visit root_path
      ....
```

I get that error : No routes matches [GET] "/rack_session/edit"

Any idea why ?

Thx !

**Comment by le0pard** [comment]
Did you add middleware in test env?

**Comment by C404** [comment]
Hi, do you mean config.middleware.use RackSessionAccess::Middleware ?

**Comment by ayanko** [comment]
Yes. You should explitly to inject this middleware into desired environment (test, cucumber). See readme doc.

**Comment by ayanko** [comment]
>I get that error : No routes matches [GET] 

@C404 what about to change nick first? :-)

**Comment by C404** [comment]
Haha yeah ;)
Otherwise you were right ... I think i jumped to fast on the Rspec part forgetting that line in the test env.
Thx !
