### ISSUE TITLE
Net::ReadTimeOut

### ISSUE THREAD

**Issue by bbtdev** [railsware/rack_session_access#28]
Hello, 
Localy everything works fine, the problem is when I try to run rspec on circleci

`AdminSubjectsController circle test 
     Failure/Error: page.set_rack_session(user_id: 1)
     
     Net::ReadTimeout:
       Net::ReadTimeout
     # ./spec/controllers/admin_subjects_controller_spec.rb:18:in `block (2 levels) in <top (required)>'
     # ./spec/rails_helper.rb:83:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:82:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # IO::EAGAINWaitReadable:
     #   Resource temporarily unavailable - read would block
     #   ./spec/controllers/admin_subjects_controller_spec.rb:18:in `block (2 levels) in <top (required)>'`

The code:
`before do

    page.set_rack_session(user_id: 1)

 end`

I would undestand if I get this error when visting a page with capybara, but I don't why on page.set_rack.

Thank you very much,

**Comment by ayanko** [comment]
Because set_rack_session is capybara helper which DO visit real page on browser by specific url which handles middleware.
