### ISSUE TITLE
Rails 5 support and CI

### ISSUE THREAD

**Issue by starsirius** [railsware/rack_session_access#29]
Hi team, I've been enjoying using this gem in our acceptance tests, and think we could keep it in a healthy state. Specifically, I wonder if we plan to:
* test it against Rails 5, and
* put it on CI so it's more visible.

Thanks!

**Comment by ayanko** [comment]
We already use it with rail5 in our project.
It definitely works.
But it also make sense to add explict test coverage.

**Comment by ayanko** [comment]
@starsirius DONE

**Comment by starsirius** [comment]
@ayanko Amazing! Thanks for helping with this over the weekend! 💯I would also suggest adding a change log for users of this gem. We use [Danger](https://github.com/danger/danger) to facilitate that and it's been great!
