### ISSUE TITLE
Capybara::ElementNotFound: Unable to find field "data" that is not disabled

### ISSUE THREAD

**Issue by chase439** [railsware/rack_session_access#33]
I'm getting this error when I upgraded from rails 5.2 to 6.0.0. It was working fine in Rails 5.2.

I think it points to these lines:

- https://github.com/railsware/rack_session_access/blob/master/lib/rack_session_access/capybara.rb#L8
- https://github.com/railsware/rack_session_access/blob/master/lib/rack_session_access/middleware.rb#L79

After some troubleshooting, this happens when there's a line like below in Rails app's config/application.rb:
- config.hosts << ENV['APP_HOST']

This line is recommended by Rails.

**Comment by ayanko** [comment]
What is your capybara version?

**Comment by chase439** [comment]
latest capybara version 3.29.0

After more troubleshooting, I found the solution.

Put in config/environments/test.rb: `config.hosts = []`

**Comment by ayanko** [comment]
Yeap https://www.fngtps.com/2019/rails6-blocked-host/

**Comment by smarquez1** [comment]
I'm getting the same error and the `config.hosts` solution does not work when if I use RackTest, it works if I use chromedriver though. Any other ideas on how to fix it?

- Rails: 4.2.11
- Capybara: 3.35
- rack_session_access: 0.2.0
- webdrivers: 4.0
